"""add last_statement_sync_at to provider_connections

Revision ID: 1697eedd2838
Revises: 9dc9f3000d7a
Create Date: 2026-07-11 22:35:18.640088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1697eedd2838'
down_revision: Union[str, Sequence[str], None] = '9dc9f3000d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_connections', sa.Column('last_statement_sync_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_connections', 'last_statement_sync_at')
    # ### end Alembic commands ###
