"""add note to transactions

Revision ID: 7060b3ffdf44
Revises: 5c80758eb560
Create Date: 2026-07-19 14:07:44.074397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7060b3ffdf44'
down_revision: Union[str, Sequence[str], None] = '5c80758eb560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'note')
    # ### end Alembic commands ###
