"""accounts and transaction source for net worth

Revision ID: 93c95cba230c
Revises: d10934b1dd7e
Create Date: 2026-10-02 21:35:54.241341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93c95cba230c'
down_revision: Union[str, Sequence[str], None] = 'd10934b1dd7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('davivienda', 'nequi', 'cash', name='account_kind'), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('opening_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', name='uq_accounts_user_kind')
    )
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('account_adjustments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reported_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_adjustments_account_id'), 'account_adjustments', ['account_id'], unique=False)
    op.add_column('transactions', sa.Column('source', sa.String(length=32), nullable=True))
    op.alter_column('transactions', 'provider_connection_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Typed-in cash expenses have no connection; they can't survive NOT NULL.
    op.execute("DELETE FROM transactions WHERE provider_connection_id IS NULL")
    op.alter_column('transactions', 'provider_connection_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('transactions', 'source')
    op.drop_index(op.f('ix_account_adjustments_account_id'), table_name='account_adjustments')
    op.drop_table('account_adjustments')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_table('accounts')
    sa.Enum(name='account_kind').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
