"""credit card email link on debts

Revision ID: d10934b1dd7e
Revises: eab7d2db244a
Create Date: 2026-10-02 21:15:24.182027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd10934b1dd7e'
down_revision: Union[str, Sequence[str], None] = 'eab7d2db244a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debts', sa.Column('email_sender', sa.String(length=255), nullable=True))
    op.add_column('debts', sa.Column('email_format', sa.String(length=32), nullable=True))
    op.add_column('debts', sa.Column('card_last_digits', sa.String(length=4), nullable=True))
    op.add_column('debts', sa.Column('payment_due_date', sa.Date(), nullable=True))
    op.add_column('debts', sa.Column('email_linked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transactions', sa.Column('debt_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_transactions_debt_id'), 'transactions', ['debt_id'], unique=False)
    op.create_foreign_key('fk_transactions_debt_id_debts', 'transactions', 'debts', ['debt_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transactions_debt_id_debts', 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_debt_id'), table_name='transactions')
    op.drop_column('transactions', 'debt_id')
    op.drop_column('debts', 'email_linked_at')
    op.drop_column('debts', 'payment_due_date')
    op.drop_column('debts', 'card_last_digits')
    op.drop_column('debts', 'email_format')
    op.drop_column('debts', 'email_sender')
    # ### end Alembic commands ###
