"""add paid_month to planned_payments

Revision ID: eab7d2db244a
Revises: 7060b3ffdf44
Create Date: 2026-07-19 15:18:40.885212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab7d2db244a'
down_revision: Union[str, Sequence[str], None] = '7060b3ffdf44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planned_payments', sa.Column('paid_month', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planned_payments', 'paid_month')
    # ### end Alembic commands ###
